name: Deploy with gh-pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install

      - run: git config --global user.email "support+actions@github.com"
      - run: git config --global user.name "github-actions-bot"
      - run: git remote set-url origin https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git

      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build

      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: deploy

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          PUBLIC_URL: /react-blog
